language: ruby
sudo: false
cache: bundler
bundler_args: '--without production development'
rvm:
  - 2.2.2
env: DATABASE_URL=postgres://postgres@localhost/timeoverflow_test
before_script:
  - bundle exec rake db:setup
services:
  - elasticsearch
