env:
  global:
    - CC_TEST_REPORTER_ID=XXXXXXX
language: ruby
cache: bundler
bundler_args: '--without development'
env: DATABASE_URL=postgres://postgres@localhost/timeoverflow_test
before_script:
  - bundle exec rake db:setup
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  # allow elasticsearch to be ready - https://docs.travis-ci.com/user/database-setup/#ElasticSearch
  - sleep 10
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
services:
  - elasticsearch
addons:
  chrome: stable
